[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_programs = "6K3aJvQqyjgNkX6J2ZVLtHBkpjDAsBXjTS7xYccpsu98"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
